### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(EagsenWindowsTool)
add_subdirectory(EagsenWindowsToolContent)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
	EagsenWindowsToolplugin
	EagsenWindowsToolContentplugin)